theme: jekyll-theme-minimal
logo: https://static.tumblr.com/a5fd4159b8bf5e51f2f9a7dc89f7e750/sinqgxr/Lohn3e404/tumblr_static_screen_shot_2014-04-01_at_11.13.29_pm.png
title: "DinaZ's Bio Informatics GitHub"

